name: scrape-mineral-hardnesses

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */1 * * *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get working version
        uses: actions/checkout@master
        with:
          fetch-depth: 1                                                                 
      - name: 🐍 Python setup                              
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.8'                                                   
      - name: Install Python dependencies                             
        run: pip install -r requirements.txt
      - name: Update the hardnesses dataset
        run: python main.py
      - name: Commit and push if the data has changed
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push